name: Build Releases
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  releases:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows]
        arch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - name: Build Binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          mkdir -p dist/
          output_name=sbctl-${{ matrix.os }}-${{ matrix.arch }}
          if [ "${{ matrix.os }}" = "windows" ]; then
            output_name="$output_name.exe"
          fi
          go build -o dist/$output_name ./
      - name: Sum
        run: |
          cd dist
          sha256sum ./* > checksums.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
