name: Build Releases
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - name: Build Binary
        run: |
          mkdir -p dist/
          export GOOS=linux
          export GOARCH=amd64
          output_name=sbctl-$GOOS-$GOARCH
          go build -o dist/$output_name ./

          export GOOS=windows
          output_name=sbctl-$GOOS-$GOARCH.exe
          go build -o dist/$output_name ./
      - name: Sum
        run: |
          cd dist
          sha256sum ./* > checksums.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
