name: Build Releases
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1
      - name: Build
        run: zig build releases -Dtag=${{ github.ref_name }}
      - name: Compress
        run: |
          mkdir zig-out/releases
          cd zig-out/targets
          /bin/ls | awk '{if (index($0, "windows") > 0) { system("zip -r ../releases/" $0 ".zip " $0) } else { system("tar -czvf ../releases/" $0 ".tar.gz " $0) }}'
      - name: Sum
        run: |
          cd zig-out/releases
          sha256sum ./* > checksums.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: zig-out/releases/*
